keystone:
  admin-password: password

mysql:
  dataset-size: 10%
  max-connections: 1000

neutron-api:
  neutron-plugin: odl
  neutron-security-groups: True

neutron-gateway:
  instance-mtu: 1400
  plugin: odl

nova-cloud-controller:
  network-manager: Neutron
  quantum-security-groups: "yes"
