#!/bin/bash
#set -x

#Add the bootstrap node that failed earier

virsh dumpxml bootstrap >bootstrap.xml
bootstrapmac=`grep  "mac address" bootstrap.xml | head -1 | cut -d "'" -f 2`

bootstrapid=`maas maas nodes new autodetect_nodegroup='yes' name='bootstrap' tags='bootstrap' hostname='bootstrap' power_type='virsh' mac_addresses=$bootstrapmac power_parameters_power_address='qemu+ssh://root@$1/system' architecture='ppc64el' power_parameters_power_id='bootstrap' | grep system_id | cut -d '"' -f 4 `

maas maas tag update-nodes bootstrap add=$bootstrapid


systems=`maas maas nodes  list |  grep system_id |  awk '{print $2}' | sed  -e 's/,$//' -e 's/^"//'  -e 's/"$//'`

for i in $systems
do
	node_name=`maas maas node read $i | grep hostname |  awk '{print $2}' | sed  -e 's/,$//' -e 's/^"//'  -e 's/"$//' | awk -F "." '{print $1}'`
	echo $i $node_name

	 maas maas node update $i power_parameters_power_pass=passw0rd power_parameters_power_address="qemu+ssh://root@$1/system" power_parameters_power_id=$node_name
done

