# This file defines the deployment for the MAAS environment which is to be
# deployed and automated.
demo-maas:
    maas:
        # Defines the general setup for the MAAS environment, including the
        # username and password for the host as well as the MAAS server.
        user: ubuntu
        password: ubuntu

        # Contains the virtual machine parameters for creating the MAAS virtual
        # server. Here you can configure the name of the virsh domain, the
        # parameters for how the network is attached.
        name: opnfv-maas-orange
        interfaces: ['bridge=brAdm,model=virtio', 'bridge=brData,model=virtio', 'bridge=brStorage,model=virtio']
        memory: 4096
        vcpus: 4
        arch: amd64
        pool: default
        disk_size: 120G

        # Apt http proxy setting(s)
        apt_http_proxy:

        apt_sources:
          - ppa:maas/next
          - ppa:juju/stable

        # Virsh power settings
        # Specifies the uri and keys to use for virsh power control of the
        # juju virtual machine. If the uri is omitted, the value for the
        # --remote is used. If no power settings are desired, then do not
        # supply the virsh block.
        virsh:
            rsa_priv_key: /home/ubuntu/.ssh/id_rsa
            rsa_pub_key: /home/ubuntu/.ssh/id_rsa.pub
            uri: qemu+ssh://ubuntu@192.168.2.4/system

        # Defines the IP Address that the configuration script will use to
        # to access the MAAS controller via SSH.
        ip_address: 192.168.2.5

        # This section allows the user to set a series of options on the
        # MAAS server itself. The list of config options can be found in
        # the upstream MAAS documentation:
        #  - http://maas.ubuntu.com/docs/api.html#maas-server
        settings:
            main_archive: http://fr.archive.ubuntu.com/ubuntu
            upstream_dns: 192.168.2.1
            maas_name: orangepod2
            # kernel_opts: "console=tty0 console=ttyS1,115200n8"
            # ntp_server: ntp.ubuntu.com

        # This section is used to define the networking parameters for when
        # the node first comes up. It is fed into the meta-data cloud-init
        # configuration and is used to configure the networking piece of the
        # service. The contents of this section are written directly to the
        # /etc/network/interfaces file.
        #
        # Please note, this is slightly different than the
        # node-group-interfaces section below. This will configure the
        # machine's networking params, and the node-group-interfaces will
        # configure the maas node-group interfaces which is used for
        # controlling the dhcp, dns, etc.
        network_config: |
            auto lo
            iface lo inet loopback

            auto eth0
            iface eth0 inet static
            address 192.168.2.5
            netmask 255.255.255.0
            network 192.168.2.0
            broadcast 192.168.2.255
            gateway 192.168.2.1
            dns-nameservers 192.168.2.1 127.0.0.1

            auto eth1
            iface eth1 inet static
            address 192.168.12.5
            netmask 255.255.255.0
            network 192.168.12.0
            broadcast 192.168.12.255

            auto eth2
            iface eth2 inet static
            address 192.168.22.5
            netmask 255.255.255.0
            network 192.168.22.0
            broadcast 192.168.22.255

            #auto lo
            #iface lo inet loopback

            #auto eth0
            #iface eth0 inet static
            #  address 192.168.122.2
            #  netmask 255.255.248.0
            #  network 192.168.122.0
            #  broadcast 192.168.122.255
            #  gateway 192.168.122.1
            #  dns-nameservers 192.168.122.1 127.0.0.1

        # The node-group-interfaces section is used to configure the MAAS
        # network interfaces. Basic configuration is supported, such as which
        # device should be bound, the range of IP addresses, etc.
        # Note: this may contain the special identifiers:
        #   ${maas_net} - the first 3 octets of the ipv4 address
        #   ${maas_ip} - the ip address of the MAAS controller
        node_group_ifaces:
            - device: eth0
              ip: 192.168.2.5
              subnet_mask: 255.255.255.0
              broadcast_ip: 192.168.2.255
              router_ip: 192.168.2.1
              static_range:
                  low: 192.168.2.50
                  high: 192.168.2.99
              dynamic_range:
                  low: 192.168.2.100
                  high: 192.168.2.200
            - device: eth1
              ip: 192.168.12.5
              subnet_mask: 255.255.255.0
              broadcast_ip: 192.168.12.255
              management: 1
              static_range:
                  low: 192.168.12.50
                  high: 192.168.12.99
              dynamic_range:
                  low: 192.168.12.100
                  high: 192.168.12.200
            - device: eth2
              ip: 192.168.22.5
              subnet_mask: 255.255.255.0
              broadcast_ip: 192.168.22.255
              management: 1
              static_range:
                  low: 192.168.22.50
                  high: 192.168.22.99
              dynamic_range:
                  low: 192.168.22.100
                  high: 192.168.22.200

        # Defines the physical nodes which are added to the MAAS cluster
        # controller upon startup of the node.
        nodes:
            - name: node1-compute
              tags: compute
              architecture: amd64/generic
              mac_addresses:
                  - "38:63:bb:3f:bc:c8"
              power:
                  type: ipmi
                  address: 192.168.2.11
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0
#              sticky_ip_address:
#                  mac_address: "38:63:bb:43:b8:9c"
#                  requested_address: 192.168.122.5
#
            - name: node2-compute
              tags: compute
              architecture: amd64/generic
              mac_addresses:
                  - "38:63:bb:44:34:84"
              power:
                  type: ipmi
                  address: 192.168.2.12
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

            - name: node3-compute
              tags: compute
              architecture: amd64/generic
              mac_addresses:
                  - "38:63:bb:3f:1d:8c"
              power:
                  type: ipmi
                  address: 192.168.2.13
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

            - name: node4-compute
              tags: compute
              architecture: amd64/generic
              mac_addresses:
                  - "38:63:bb:3f:2d:a8"
              power:
                  type: ipmi
                  address: 192.168.2.14
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

            - name: node5-control
              tags: control
              architecture: amd64/generic
              mac_addresses:
                  - "94:57:a5:52:c9:48"
              power:
                  type: ipmi
                  address: 192.168.2.15
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

            - name: node6-control
              tags: control
              architecture: amd64/generic
              mac_addresses:
                  - "94:57:a5:52:63:b0"
              power:
                  type: ipmi
                  address: 192.168.2.16
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

            - name: node7-control
              tags: control
              architecture: amd64/generic
              mac_addresses:
                  - "94:57:a5:52:f1:80"
              power:
                  type: ipmi
                  address: 192.168.2.17
                  user: Administrator
                  pass: pod2Admin
                  driver: LAN_2_0

    # Contains the virtual machine parameters for creating the Juju bootstrap
    # node virtual machine
    juju-bootstrap:
        name: bootstrap
        interfaces: ['bridge=brAdm,model=virtio']
        memory: 4096
        vcpus: 2
        arch: amd64
        pool: default
        disk_size: 60G
